export const cardTypes = ['Link','Text','Image','Video','Music','Spotify','Discord','Roblox','YouTube','TikTok','Twitch','Gallery','Countdown','FAQ','Donate','Contact','Socials','Custom embed'];
export const sampleProfiles = [
  { username:'preston', slug:'preston', headline:'Founder of PrestonHQ • building creator tools', bio:'Dark cyber profile, creator links, Discord hub, updates, showcases, and everything PrestonHQ in one place.', avatarUrl:'/favicon.svg', bannerUrl:'', views:12842, badges:['Founder','Verified','Early access'], socials:[{label:'Discord',url:'#'},{label:'YouTube',url:'#'},{label:'Roblox',url:'#'}], cards:[{type:'LINK',title:'Join the PrestonHQ Discord',body:'Updates, drops, support, and community events.',url:'#'},{type:'YOUTUBE',title:'Latest build showcase',body:'A quick look at the new PrestonHQ Profiles platform.',safeEmbedUrl:'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ'},{type:'COUNTDOWN',title:'Public beta launch',body:'Launching soon with free themes, analytics, and creator cards.'}]},
  { username:'liberty', slug:'liberty', headline:'ERLC community owner', bio:'Sessions, staff apps, events, and community links.', avatarUrl:'/favicon.svg', bannerUrl:'', views:7921, badges:['Community','Partner'], socials:[{label:'Roblox',url:'#'},{label:'TikTok',url:'#'}], cards:[{type:'DISCORD',title:'Community server',body:'Join for sessions and announcements.',url:'#'}]},
  { username:'icesway', slug:'icesway', headline:'Streamer • YouTube • Kick • Twitch', bio:'Live alerts, uploads, clips, and socials.', avatarUrl:'/favicon.svg', bannerUrl:'', views:5390, badges:['Creator'], socials:[{label:'YouTube',url:'#'},{label:'Twitch',url:'#'}], cards:[{type:'TWITCH',title:'Live schedule',body:'Weekends and random late-night streams.',url:'#'}]}
];
export const themePresets = [
  {name:'Nebula Glass', accent:'#7c5cff', glow:'#2fffd1'}, {name:'Cyber Rose', accent:'#ff4fd8', glow:'#ffb86b'}, {name:'Arctic Neon', accent:'#2fffd1', glow:'#76a9ff'}, {name:'Inferno', accent:'#ff7a1a', glow:'#ff4fd8'}
];
export const activity = ['preston published a new video card','liberty passed 7k profile views','icesway enabled live notifications','new theme marketplace pack approved','3 reports resolved by moderation'];