(() => {
  const API = 'api/profiles.php';
  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];
  const app = $('#app');
  const starter = { username:'preston', displayName:'Preston', headline:'Builder of bots, communities, and clean chaos.', bio:'Welcome to my PrestonHQ profile — links, videos, music, cards, badges, and everything in one glossy page.', avatar:'', banner:'', backgroundVideo:'', music:'', font:'Inter', cursor:'neon', branding:true, theme:{name:'Cyber Glass',accent:'#66f7ff',accent2:'#ff4ecd',glass:72,radius:26}, effects:{particles:true,rain:false,snow:false,glow:true}, socials:[{type:'discord',label:'Discord Server',url:'https://discord.gg/prestonhq'},{type:'youtube',label:'YouTube',url:'https://youtube.com/@prestonhq'},{type:'tiktok',label:'TikTok',url:'https://tiktok.com/@prestonhq'},{type:'roblox',label:'Roblox',url:'https://roblox.com'},{type:'spotify',label:'Spotify',url:'https://spotify.com'}], badges:['Founder','Verified Soon','Bot Dev'], cards:[{type:'link',title:'Join the community',body:'Hop in and see what PrestonHQ is building.',url:'https://prestonhq.com'},{type:'video',title:'Featured video',body:'Safe YouTube/TikTok embeds only.',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ'},{type:'discord',title:'Discord server',body:'Live community card ready for API stats.',url:'https://discord.gg/prestonhq'},{type:'countdown',title:'Next drop',body:'Launching soon',date:'2026-12-31T23:59:00'}], analytics:{views:12840,visitors:4210,clicks:2930,today:247}, moderation:{status:'public',featured:true,verified:false} };
  const state = { me: JSON.parse(localStorage.getItem('phq_user') || 'null'), profile: JSON.parse(localStorage.getItem('phq_profile') || 'null') || starter, profiles: JSON.parse(localStorage.getItem('phq_profiles') || '{}') };
  state.profiles.preston = starter;
  function saveLocal(){ localStorage.setItem('phq_user',JSON.stringify(state.me)); localStorage.setItem('phq_profile',JSON.stringify(state.profile)); state.profiles[state.profile.username||'me']=state.profile; localStorage.setItem('phq_profiles',JSON.stringify(state.profiles)); }
  async function api(action,payload={}){ try{ const res=await fetch(API+'?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)}); return await res.json(); }catch{return{ok:false,offline:true};} }
  function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function socialIcon(type){return({discord:'💬',youtube:'▶️',tiktok:'♪',roblox:'⬡',spotify:'🎧',link:'🔗',kick:'🟢',twitch:'🟣',music:'🎧',video:'🎬',image:'🖼',countdown:'⏳',donation:'💸'}[type]||'🔗');}
  function validUrl(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
  function safeEmbedUrl(url){try{const u=new URL(url); if(u.hostname.includes('youtube.com')&&u.searchParams.get('v'))return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(u.searchParams.get('v'))}`; if(u.hostname==='youtu.be')return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(u.pathname.slice(1))}`; if(u.hostname.includes('tiktok.com'))return validUrl(url);}catch{} return null;}
  function cardHtml(c){const title=escapeHtml(c.title||c.type||'Card'),body=escapeHtml(c.body||''); if(c.type==='video'){const embed=safeEmbedUrl(c.url||''); return `<div class="custom-card" style="display:block"><b>🎬 ${title}</b><p>${body}</p>${embed&&embed.includes('youtube')?`<iframe title="${title}" width="100%" height="210" style="border:0;border-radius:14px" loading="lazy" allowfullscreen src="${escapeHtml(embed)}"></iframe>`:`<a href="${escapeHtml(validUrl(c.url))}" target="_blank" rel="noopener">Open video ↗</a>`}</div>`;} if(c.type==='image')return `<div class="custom-card" style="display:block"><b>🖼 ${title}</b><p>${body}</p><img src="${escapeHtml(validUrl(c.url))}" alt="${title}" loading="lazy" style="width:100%;border-radius:14px"></div>`; if(c.type==='countdown')return `<div class="custom-card"><span><b>⏳ ${title}</b><br><small>${body}</small></span><span data-countdown="${escapeHtml(c.date||'')}">Soon</span></div>`; return `<a class="custom-card" href="${escapeHtml(validUrl(c.url))}" target="_blank" rel="noopener noreferrer"><span><b>${socialIcon(c.type)} ${title}</b><br><small>${body}</small></span><span>↗</span></a>`;}
  function profileCard(profile=state.profile,full=false){const p={...starter,...profile}; const avatar=p.avatar?`<img class="avatar" src="${escapeHtml(validUrl(p.avatar))}" alt="${escapeHtml(p.displayName)} avatar">`:`<div class="avatar"></div>`; const socials=(p.socials||[]).map(s=>`<a class="social-link" href="${escapeHtml(validUrl(s.url))}" target="_blank" rel="noopener noreferrer"><span class="social-left"><span class="social-icon">${socialIcon(s.type)}</span><b>${escapeHtml(s.label||s.type)}</b></span><span>↗</span></a>`).join(''); const badges=(p.badges||[]).map(b=>`<span class="badge">✦ ${escapeHtml(b)}</span>`).join(''); const cards=(p.cards||[]).map(cardHtml).join(''); const effects=p.effects||{}; return `${p.backgroundVideo?`<video class="profile-page-bg" autoplay muted loop playsinline src="${escapeHtml(validUrl(p.backgroundVideo))}"></video>`:''}${full?`<div class="effect-layer ${effects.rain?'rain':effects.snow?'snow':effects.particles?'particles':''}"></div>`:''}<article class="profile-card" style="--banner:url('${escapeHtml(validUrl(p.banner))}'); border-radius:${Number(p.theme?.radius||26)}px"><div class="profile-banner"></div><div class="profile-body">${avatar}<div class="profile-title"><h2>${escapeHtml(p.displayName||p.username)}</h2><div class="badges">${badges}</div></div><p class="bio"><b>${escapeHtml(p.headline||'')}</b><br>${escapeHtml(p.bio||'')}</p><div class="socials">${socials}</div>${p.music?`<div class="music-player"><b>🎧 Now playing</b><audio controls preload="none" src="${escapeHtml(validUrl(p.music))}"></audio></div>`:''}<div class="card-list">${cards}</div><div class="counter">👁 ${Number(p.analytics?.views||0).toLocaleString()} views • PrestonHQ Profiles</div></div></article>`;}
  function renderLanding(){app.innerHTML=$('#landing-template').innerHTML+pricingSection(); $('[data-demo-profile]').innerHTML=profileCard(starter);} 
  function pricingSection(){return `<section id="pricing" class="section"><div class="section-head"><span class="eyebrow"><span></span> Pricing path</span><h2>Free now. Premium-ready later.</h2></div><div class="pricing-grid"><div class="price-card"><h3>Free</h3><p>Launch a powerful profile without paying.</p><ul><li>Unlimited links</li><li>Basic themes</li><li>Custom cards</li><li>Image/video backgrounds</li><li>Music upload/link</li><li>Particles, rain, snow, glow</li><li>Safe YouTube/TikTok embeds</li><li>Badges, fonts, basic analytics</li></ul></div><div class="price-card"><h3>Future Premium</h3><p>Built into the roadmap, not forced today.</p><ul><li>Premium themes and advanced effects</li><li>Custom domains</li><li>Verified badge</li><li>Private profiles</li><li>No PrestonHQ branding</li><li>Multiple pages/tabs</li><li>Shop/product cards</li><li>Priority placement</li></ul></div></div></section>`;}
  function renderAuth(mode){app.innerHTML=$('#auth-template').innerHTML; const signup=mode==='signup'; $('[data-auth-title]').textContent=signup?'Create your profile':'Welcome back'; $('[data-auth-copy]').textContent=signup?'Claim your username and start building PrestonHQ Profiles.':'Login to edit your profile, cards, effects, and analytics.'; $('[data-email-field]').style.display=signup?'grid':'none'; $('[data-auth-submit]').textContent=signup?'Create account':'Login'; $('[data-auth-switch]').innerHTML=signup?'Already have one? <a href="#/login">Login</a>':'New here? <a href="#/signup">Create an account</a>'; $('#authForm').addEventListener('submit',async e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.currentTarget)); const res=await api(signup?'signup':'login',data); state.me=res.user||{username:data.username,role:data.username==='admin'?'admin':'user'}; state.profile=res.profile||{...starter,username:data.username,displayName:data.username}; saveLocal(); location.hash='#/dashboard';});}
  function renderDashboard(panel='overview'){if(!state.me){location.hash='#/login';return;} app.innerHTML=$('#dashboard-template').innerHTML; $$('.dash-sidebar button').forEach(b=>{b.classList.toggle('active',b.dataset.panel===panel); b.onclick=()=>renderDashboard(b.dataset.panel);}); $('#saveProfileBtn').onclick=saveProfile; $('#publishProfileBtn').onclick=saveProfile; renderPanel(panel);} 
  function renderPanel(panel){const root=$('#dashboardPanel'),p=state.profile; if(panel==='overview')root.innerHTML=`<div class="widget-grid"><div class="widget" draggable="true"><strong>${Number(p.analytics.views).toLocaleString()}</strong><span>Profile views</span></div><div class="widget" draggable="true"><strong>${Number(p.analytics.today).toLocaleString()}</strong><span>Views today</span></div><div class="widget" draggable="true"><strong>${p.socials.length}</strong><span>Social links</span></div><div class="widget" draggable="true"><strong>${p.cards.length}</strong><span>Custom cards</span></div></div><div class="section split-panel"><div><h2>Launch checklist</h2><p>Add avatar/banner, connect socials, choose effects, add cards, and publish.</p></div><div class="mini-dashboard"><span class="dash-chip">Auth ready</span><span class="dash-chip">Safe embeds</span><span class="dash-chip">Rate-limit API</span><span class="dash-chip">Admin moderation</span></div></div>`; if(panel==='profile')root.innerHTML=editorPanel(); if(panel==='theme')root.innerHTML=themePanel(); if(panel==='cards')root.innerHTML=cardsPanel(); if(panel==='effects')root.innerHTML=effectsPanel(); if(panel==='analytics')root.innerHTML=analyticsPanel(); if(panel==='admin')root.innerHTML=adminPanel(); bindEditors();}
  function editorPanel(){const p=state.profile;return `<div class="editor-grid"><div><div class="editor-card"><h3>Profile identity</h3><form class="stack-form" data-edit="profile"><div class="two-col"><label>Username<input name="username" value="${escapeHtml(p.username)}"></label><label>Display name<input name="displayName" value="${escapeHtml(p.displayName)}"></label></div><label>Headline<input name="headline" value="${escapeHtml(p.headline)}"></label><label>Bio<textarea name="bio">${escapeHtml(p.bio)}</textarea></label><label>Avatar URL<input name="avatar" value="${escapeHtml(p.avatar)}" placeholder="https://..."></label><label>Banner URL<input name="banner" value="${escapeHtml(p.banner)}" placeholder="https://..."></label><label>Video background URL<input name="backgroundVideo" value="${escapeHtml(p.backgroundVideo)}" placeholder="mp4/webm link"></label><label>Music URL<input name="music" value="${escapeHtml(p.music)}" placeholder="mp3/ogg link"></label></form></div><div class="editor-card"><h3>Social links</h3><div id="socialRows">${p.socials.map((s,i)=>socialRow(s,i)).join('')}</div><button class="btn ghost" data-add-social>Add social</button></div></div><div class="preview-sticky">${profileCard(p)}</div></div>`}
  function socialRow(s,i){return `<div class="card-row" data-social-row="${i}"><select data-social="type"><option>${escapeHtml(s.type)}</option><option>discord</option><option>youtube</option><option>tiktok</option><option>roblox</option><option>spotify</option><option>link</option></select><input data-social="label" value="${escapeHtml(s.label)}"><input data-social="url" value="${escapeHtml(s.url)}"><button class="btn small ghost" data-remove-social="${i}">Remove</button></div>`}
  function themePanel(){const t=state.profile.theme;return `<div class="editor-grid"><div class="editor-card"><h3>Theme editor</h3><form class="stack-form" data-edit="theme"><label>Theme name<input name="name" value="${escapeHtml(t.name)}"></label><div class="two-col"><label>Accent<input type="color" name="accent" value="${escapeHtml(t.accent)}"></label><label>Accent 2<input type="color" name="accent2" value="${escapeHtml(t.accent2)}"></label></div><label>Card radius<input type="range" min="12" max="42" name="radius" value="${Number(t.radius)}"></label><label>Glass strength<input type="range" min="20" max="95" name="glass" value="${Number(t.glass)}"></label><label>Custom font<select name="font"><option>Inter</option><option>JetBrains Mono</option><option>System</option></select></label></form></div><div class="preview-sticky">${profileCard(state.profile)}</div></div>`}
  function cardsPanel(){const p=state.profile;return `<div class="editor-card"><h3>Custom cards</h3><p>Supported: link, video, music, Discord server, Roblox profile/game, image gallery, announcement, countdown, donation. Custom HTML is admin-trusted only.</p><div class="cards-manager">${p.cards.map((c,i)=>`<div class="card-row" data-card-row="${i}"><select data-card="type"><option>${escapeHtml(c.type)}</option><option>link</option><option>video</option><option>music</option><option>discord</option><option>roblox</option><option>image</option><option>announcement</option><option>countdown</option><option>donation</option></select><input data-card="title" value="${escapeHtml(c.title)}"><input data-card="url" value="${escapeHtml(c.url||c.date||'')}" placeholder="URL/date"><button class="btn small ghost" data-remove-card="${i}">Remove</button></div>`).join('')}</div><button class="btn primary" data-add-card>Add card</button></div>`}
  function effectsPanel(){const e=state.profile.effects;return `<div class="editor-card"><h3>Effects system</h3><div class="toggle-grid">${['particles','rain','snow','glow'].map(k=>`<button class="toggle ${e[k]?'active':''}" data-effect="${k}">${e[k]?'✓':'+'} ${k}</button>`).join('')}</div><p style="margin-top:18px">Custom cursor is enabled with a neon cursor layer. Paid-ready effects can be added later.</p></div>`}
  function analyticsPanel(){const a=state.profile.analytics;return `<div class="widget-grid"><div class="widget"><strong>${a.views}</strong><span>Total views</span></div><div class="widget"><strong>${a.visitors}</strong><span>Unique visitors</span></div><div class="widget"><strong>${a.clicks}</strong><span>Link clicks</span></div><div class="widget"><strong>${a.today}</strong><span>Today</span></div></div><div class="editor-card"><h3>Basic analytics</h3><p>API model supports view events, click events, referrers, devices, and future advanced analytics upgrades.</p></div>`}
  function adminPanel(){return `<div class="editor-card"><h3>Admin panel</h3><p>Moderate profiles, feature creators, verify users, lock unsafe cards, and review uploads.</p><div class="admin-table"><div class="admin-row"><b>@${escapeHtml(state.profile.username)}</b><span>${state.profile.moderation.status}</span><button class="btn small ghost">Review</button></div><div class="admin-row"><b>Custom HTML cards</b><span>Trusted only</span><button class="btn small ghost">Manage</button></div><div class="admin-row"><b>Rate limits</b><span>Active</span><button class="btn small ghost">View</button></div></div></div>`}
  function bindEditors(){
    $$('[data-edit="profile"] input,[data-edit="profile"] textarea').forEach(el=>el.oninput=()=>{state.profile[el.name]=el.value;saveLocal();renderPanel('profile')});
    $$('[data-edit="theme"] input,[data-edit="theme"] select').forEach(el=>el.oninput=()=>{state.profile.theme[el.name]=el.type==='range'?Number(el.value):el.value;saveLocal();renderPanel('theme')});
    $('[data-add-social]')?.addEventListener('click',()=>{state.profile.socials.push({type:'link',label:'New link',url:'https://'});saveLocal();renderPanel('profile')});
    $$('[data-remove-social]').forEach(b=>b.onclick=()=>{state.profile.socials.splice(Number(b.dataset.removeSocial),1);saveLocal();renderPanel('profile')});
    $$('[data-social-row]').forEach(row=>$$('[data-social]',row).forEach(input=>input.onchange=()=>{state.profile.socials[Number(row.dataset.socialRow)][input.dataset.social]=input.value;saveLocal()}));
    $('[data-add-card]')?.addEventListener('click',()=>{state.profile.cards.push({type:'link',title:'New card',body:'Add details',url:'https://'});saveLocal();renderPanel('cards')});
    $$('[data-remove-card]').forEach(b=>b.onclick=()=>{state.profile.cards.splice(Number(b.dataset.removeCard),1);saveLocal();renderPanel('cards')});
    $$('[data-card-row]').forEach(row=>$$('[data-card]',row).forEach(input=>input.onchange=()=>{const c=state.profile.cards[Number(row.dataset.cardRow)]; if(input.dataset.card==='url'&&c.type==='countdown') c.date=input.value; else c[input.dataset.card]=input.value; saveLocal()}));
    $$('[data-effect]').forEach(b=>b.onclick=()=>{const k=b.dataset.effect;state.profile.effects[k]=!state.profile.effects[k];saveLocal();renderPanel('effects')});
  }
  async function saveProfile(){ saveLocal(); await api('save-profile',{profile:state.profile}); alert('Saved PrestonHQ profile draft.'); }
  async function renderPublic(username){ let profile=username==='me'?state.profile:state.profiles[username]||null; const res=await api('profile',{username}); if(res.ok&&res.profile)profile=res.profile; profile||={...starter,username,displayName:username}; profile.analytics={...starter.analytics,...profile.analytics,views:Number(profile.analytics?.views||0)+1}; app.innerHTML=$('#profile-template').innerHTML; $('#publicProfile').innerHTML=profileCard(profile,true); tickCountdowns(); }
  function tickCountdowns(){ $$('[data-countdown]').forEach(el=>{const d=new Date(el.dataset.countdown).getTime(); if(!d)return; const diff=Math.max(0,d-Date.now()); const days=Math.floor(diff/86400000); const hrs=Math.floor(diff%86400000/3600000); const mins=Math.floor(diff%3600000/60000); el.textContent=days?`${days}d ${hrs}h`:`${hrs}h ${mins}m`;}); }
  setInterval(tickCountdowns,30000);
  function route(){const cleanPath=location.pathname.replace(/^\/+|\/+$/g,''); const pathParts=cleanPath.split('/'); if(pathParts[0]==='u'&&pathParts[1])return renderPublic(pathParts[1]); const hash=location.hash||'#/'; const parts=hash.replace(/^#\/?/,'').split('/'); const page=parts[0]||''; if(!page)return renderLanding(); if(page==='login'||page==='signup')return renderAuth(page); if(page==='dashboard')return renderDashboard(); if(page==='u')return renderPublic(parts[1]||'preston'); if(page==='features'||page==='pricing'||page==='explore'){renderLanding(); setTimeout(()=>document.getElementById(page)?.scrollIntoView(),50); return;} renderLanding();}
  document.addEventListener('mousemove',e=>{const c=$('.cursor-dot'); if(c){c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';}});
  document.querySelector('.mobile-menu')?.addEventListener('click',()=>document.querySelector('.site-nav nav')?.classList.toggle('open'));
  window.addEventListener('hashchange',route); route(); saveLocal();
})();
