import { motion } from "framer-motion";
import { Activity, Bot, Cpu, FolderGit2, MemoryStick, RadioTower, RefreshCw, ShieldCheck, Signal } from "lucide-react";
import type { BotCatalog, BotStatus } from "../types";
import { fmtUptime } from "../constants";

export function BotOverview({ bot, liveStatus }: { bot: BotCatalog; liveStatus?: BotStatus }) {
  const status = liveStatus || bot.status;
  const online = status.online;
  return (
    <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="panel animated-border relative overflow-hidden p-5 sm:p-6 lg:p-7" style={{ "--accent": bot.accent, boxShadow: `0 34px 100px -50px ${bot.accent}77` } as React.CSSProperties}>
      <div className="absolute -right-20 -top-20 h-56 w-56 rounded-full opacity-20 blur-3xl" style={{ background: bot.accent }} />
      <div className="absolute inset-x-6 bottom-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />
      <div className="flex flex-col gap-6 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex items-start gap-4">
          <div className="relative grid h-20 w-20 shrink-0 place-items-center rounded-[28px] text-3xl font-black text-[#07070b] shadow-[0_18px_60px_-24px_rgba(0,0,0,.95)]" style={{ background: `linear-gradient(135deg, ${bot.accent}, #f0abfc)` }}>{bot.name[0]}<span className={`absolute -right-1 -top-1 h-4 w-4 rounded-full border-2 border-ink-950 ${online ? "bg-emerald-400" : "bg-rose-400"}`}>{online && <span className="absolute inset-0 animate-ping rounded-full bg-emerald-400" />}</span></div>
          <div className="min-w-0"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-2.5 py-1 text-[10px] font-black uppercase tracking-[.16em] text-zinc-500"><RadioTower size={12} style={{ color: bot.accent }} /> Bot overview</div><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl">{bot.name}</h2><p className="mt-2 max-w-2xl text-[13px] leading-relaxed text-zinc-400">PM2 <span className="font-mono text-zinc-200">{bot.pm2}</span> · Prefix <span className="font-mono text-zinc-200">{bot.prefix}</span> · {bot.stats.total} commands indexed from the VPS source.</p></div>
        </div>
        <div className="min-w-[250px] rounded-3xl border border-white/10 bg-black/22 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-600">Runtime</div><div className={`mt-1 text-lg font-black ${online ? "text-emerald-300" : "text-rose-300"}`}>{online ? "Online" : status.status || "Offline"}</div></div><div className={`grid h-12 w-12 place-items-center rounded-2xl border ${online ? "border-emerald-400/20 bg-emerald-500/10 text-emerald-300" : "border-rose-400/20 bg-rose-500/10 text-rose-300"}`}><Signal size={20} /></div></div><div className="mt-4 h-2 overflow-hidden rounded-full border border-white/10 bg-black/30"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 via-cyan-300 to-brand-400" style={{ width: online ? "82%" : "18%", animation: online ? "pulse-bar 3s ease-in-out infinite" : undefined }} /></div></div>
      </div>
      <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-7"><Stat label="Total" value={bot.stats.total} accent={bot.accent} icon={Bot} /><Stat label="Slash" value={bot.stats.slash} accent="#38bdf8" icon={ShieldCheck} /><Stat label="Prefix" value={bot.stats.prefix} accent="#a78bfa" icon={Activity} /><Stat label="Auto" value={bot.stats.automation} accent="#34d399" icon={RadioTower} /><Stat label="PM2" value={status.status} accent={bot.accent} small icon={Signal} /><Stat label="Uptime" value={fmtUptime(status.uptime)} accent={bot.accent} small icon={RefreshCw} /><Stat label="Memory" value={status.memoryMb != null ? `${status.memoryMb} MB` : "—"} accent={bot.accent} small icon={MemoryStick} /></div>
      <div className="mt-5 grid gap-3 text-[11.5px] text-zinc-500 lg:grid-cols-3"><Meta icon={FolderGit2} label="Source" value={bot.root} /><Meta icon={RefreshCw} label="Restarts" value={status.restarts != null ? `${status.restarts}` : "Waiting for API"} /><Meta icon={Cpu} label="CPU" value={status.cpu != null ? `${status.cpu}%` : "Live status fallback"} /></div>
    </motion.section>
  );
}
function Stat({ label, value, accent, small, icon: Icon }: { label: string; value: string | number; accent: string; small?: boolean; icon: typeof Activity }) { return <div className="relative overflow-hidden rounded-3xl border border-white/[.075] bg-white/[.028] px-3 py-3.5 transition hover:border-white/14 hover:bg-white/[.045]"><div className="absolute -right-6 -top-6 h-16 w-16 rounded-full opacity-20 blur-2xl" style={{ background: accent }} /><div className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-[.14em] text-zinc-600"><Icon size={12} style={{ color: accent }} /> {label}</div><div className={`mt-1 truncate font-black ${small ? "text-[13px]" : "text-2xl"}`} style={{ color: accent }}>{value}</div></div>; }
function Meta({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="flex items-center gap-2 rounded-2xl border border-white/[.06] bg-black/20 px-3 py-2.5"><Icon size={14} className="shrink-0 text-zinc-500" /><span className="shrink-0 font-bold text-zinc-400">{label}:</span><span className="truncate font-mono text-zinc-600">{value}</span></div>; }
